# Generated by Django 3.2.13 on 2022-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_life_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='life_goals',
            field=models.TextField(blank=True),
        ),
    ]
